/* ============================================================
   Report Email Notification — /api/reports/[id]
   ============================================================
   Sends a notification email via Resend when a report is
   complete. Called from the report generation endpoint.
   ============================================================ */

import { NextResponse } from 'next/server';
import { Resend } from 'resend';
import type { ReportContent } from '@/types';
import { formatCurrency } from '@/lib/utils';

// Lazy-initialize Resend to avoid build-time errors when key isn't set
function getResend() {
  return new Resend(process.env.RESEND_API_KEY);
}

export async function POST(request: Request) {
  try {
    const { email, companyName, reportId, reportContent } = await request.json() as {
      email: string;
      companyName: string;
      reportId: string;
      reportContent: ReportContent;
    };

    if (!email || !companyName || !reportId) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000';
    const reportUrl = `${baseUrl}/dashboard/report/${reportId}`;
    const currency = reportContent?.valuationSummary?.currency || 'USD';

    // Extract valuation data for the email
    const centralEstimate = reportContent?.valuationSummary?.finalRange?.central;
    const topDrivers = reportContent?.keyValueDrivers?.slice(0, 3) || [];

    // Build the HTML email
    const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body style="margin:0;padding:0;background-color:#F5F5F5;font-family:'Inter',Arial,sans-serif;">
      <div style="max-width:600px;margin:0 auto;background-color:#ffffff;">
        <!-- Header -->
        <div style="background-color:#0F1C2E;padding:32px;text-align:center;">
          <h1 style="color:#C9A84C;font-size:28px;margin:0;font-weight:bold;">Valtiq</h1>
        </div>

        <!-- Content -->
        <div style="padding:32px;">
          <h2 style="color:#0F1C2E;font-size:22px;margin:0 0 16px;">
            Your Report Is Ready
          </h2>
          <p style="color:#555;font-size:15px;line-height:1.6;margin:0 0 24px;">
            Your valuation report for <strong>${companyName}</strong> has been
            generated and is ready to view.
          </p>

          ${centralEstimate ? `
          <!-- Valuation box -->
          <div style="background-color:#0F1C2E;border-radius:12px;padding:24px;text-align:center;margin:0 0 24px;">
            <p style="color:rgba(255,255,255,0.6);font-size:12px;text-transform:uppercase;letter-spacing:1px;margin:0 0 8px;">
              Central Estimate
            </p>
            <p style="color:#C9A84C;font-size:32px;font-weight:bold;margin:0;">
              ${formatCurrency(centralEstimate, currency)}
            </p>
          </div>
          ` : ''}

          ${topDrivers.length > 0 ? `
          <!-- Top value drivers -->
          <div style="margin:0 0 24px;">
            <p style="color:#0F1C2E;font-size:14px;font-weight:600;margin:0 0 12px;">
              Top Value Drivers
            </p>
            ${topDrivers.map((d: any) => `
              <div style="display:flex;align-items:flex-start;gap:8px;margin:0 0 8px;">
                <span style="color:#C9A84C;font-size:16px;">&#9679;</span>
                <span style="color:#555;font-size:14px;">${d.driver}</span>
              </div>
            `).join('')}
          </div>
          ` : ''}

          <!-- CTA Button -->
          <div style="text-align:center;margin:32px 0;">
            <a href="${reportUrl}"
               style="display:inline-block;background-color:#C9A84C;color:#0F1C2E;
                      font-weight:600;text-decoration:none;padding:14px 32px;
                      border-radius:8px;font-size:15px;">
              View Full Report
            </a>
          </div>

          <p style="color:#999;font-size:12px;line-height:1.5;margin:24px 0 0;text-align:center;">
            This report was generated by Valtiq AI Advisory and is intended for
            informational purposes only. It does not constitute financial advice.
          </p>
        </div>

        <!-- Footer -->
        <div style="background-color:#0F1C2E;padding:16px;text-align:center;">
          <p style="color:rgba(255,255,255,0.4);font-size:12px;margin:0;">
            &copy; 2025 Valtiq. All rights reserved.
          </p>
        </div>
      </div>
    </body>
    </html>
    `;

    // Send the email via Resend
    const { error: sendError } = await getResend().emails.send({
      from: 'Valtiq <reports@valtiq.com>',
      to: email,
      subject: `Your Valtiq Valuation Report for ${companyName} is ready`,
      html: htmlContent,
    });

    if (sendError) {
      console.error('Resend error:', sendError);
      return NextResponse.json({ error: 'Failed to send email' }, { status: 500 });
    }

    return NextResponse.json({ success: true });
  } catch (error: any) {
    console.error('Email notification error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to send email' },
      { status: 500 }
    );
  }
}
